[keywords]

A01 = [
    "motor neuron",
    "plasticity",
    "Plastin 3",
    "amyotropic lateral sclerosis",
    "spinal muscular atrophy",
    "mouse model",
    "cellular",
    "molecular",
    "in vivo",
    ]

A02 = [
    "ataxia",
    "cerebellum",
    "endocytosis",
    "GRID2",
    "3D Reconstruction",
    "synapse",
    "AP-2",
    ]

A03 = [
    "Purkinje cell",
    "motor learning",
    "plasticity",
    "mouse model",
    "disruptrd cerebellar motor learning",
    "ataxia",
    ]

A04 = [
    "reward",
    "locomotor behaviour",
    "mouse model",
    "ventral tegmental area",
    "lateral hypothalamus",
    "ageing",
    "obesity",
    "optogenetics",
    "calcium imaging",
    "electrophysiological",
    ]

A05 = [
   "locomotor behaviour",
   "fruit fly",
   "neurogenetic",
   "optophysiological",
   "proprioceptive feedback",
   "ascending/descending pathways",
   ]

A06 = [
    "motor cortex",
    "somatosensory cortex",
    "sensory afferents",
    "cerebellum",
    "ataxia",
    "monkey",
    "invasive recordings",
    "reaching tasks",
    ]

A07 = [
    "synaptic lipid",
    "cortical excitability",
    "brain disorders",
    ]

B01 = [
    "mouse model",
    "ion channel mutations",
    "basal ganglia",
    "thalamus",
    "c-Fos expression mapping",
    "in-vivo electrophysiological recordings",
    "fibre photometry",
    "developmental disorders",
    ]

B02 = [
    "motor network maturation",
    "children",
    "adolescents",
    "multi-channel EEG source localisation",
    "transcranial magnetic stimulation",
    "functional MRI",
    "cortical activation",
    "involuntary tic movements",
    ]

B03 = [
    "computational modelling",
    "cortical network connectivity",
    "causality",
    "simulation",
    "neurological disorders",
    "neurobiological",
    "ageing",
]	

B04 = [
    "predictability",
    "uncertainty",
    "computational modelling",
    "functional MRI",
    "simulated lesions",
    ]

B05 = [
    "neurobiological",
    "inter-individual differences",
    "functional MRI",
    "structural MRI",
    "multivariate statistical learning",
    "ageing",
    "ischemic stroke",
    "transfer-learning",
    ]

C01 = [
    "cell biology",
    "systems neuroscience",
    "spontaneous motor recovery",
    "stroke",
    "transcranial direct current stimulation",
    "tDCS",
    "mouse model",
    ]

C03 = [
    "progressive dopamine deficiency",
    "vigorous volitional movements",
    "Parkinson’s disease",
    "structural networks",
    "functional networks",
    "neuroimaging",
    "dynamic network states",
    ]

C04 = [
    "neurodegeneration-induced apraxia",
    "Alzheimer’s disease",
    "tau-pathology",
    "cortical networks",
    "neuropsychological profiling",
    "Cologne apraxia screening",
    "Tau-PET imaging",
    "functional MRI",
    ]

C05 = [
    "functional MRI",
    "simultaneous TMS-EEG",
    "online-TMS interference",
    "premotor cortex",
    "primary motor cortex",
    "stroke",
    "recovery",
    "theta-burst rTMS",
    ]

C06 = [
    "primary sympathetic effectors",
    "task-based fMRI",
    "functional MRI",
    "effective connectivity",
    "humans",
    "pro-dopaminergic treatment",
    "inflammation",
    "major depression",
    ]

C07 = [
    "real-time measurements",
    "preceding urge phenomena",
    "high-density EEG",
    "thalamic local field potentials",
    "impulsive urges to move",
    "deep brain stimulation",
    "structural connectomics",
    "sensorimotor gating",
    ]

INF = [
    "data management",
    "tools",
    "services",
    "training",
    "data analysis",
    "computational modelling",
    "workflows",
    "data access",
    "processing",
    ]

JRG_Gatto = [
    "spinal cord",
    "sensory ganglia",
    "ethologically relevant behaviors",
    "chronic pain",
    "itching",
    "spasticity",
    "neuron population imaging",
    ]

JRG_Valtcheva = [
    "adult-infant interactions",
    "behavioral motifs",
    "mouse model",
    "new mothers",
    "sensory-hormonal-motor coupling",
    "postpartum conditions",
    ]

X01 = [
    "cross-linking",
    "rehabilitation",
    "restoration",
    "mild Traumatic Brain Injury",
    "mild TBI",
    "transcranial direct current stimulation",
    "tDCS",
    ]

X02 = [
    "cross-linking",
    "sleep",
    "depressivity",
    "motor performance",
    "individual performance",
    ]

X03 = [
    "cross-linking",
    "deep brain stimulation",
    "subthalamic nucleus",
    "STN-DBS",
    "gait",
    "falls",
    "Freezing of Gait",
    "Parkinson's disease",
    "Human",
    "Animal",
    ]

X04 = [
    "cross-linking",
    "cortical network modulation",
    "predictive motor control",
    "subthalamic nucleus",
    "deep brain stimulation",
    "functional MRI",
    ]

Z01 = [
    "central office",
    "outreach",
    "coordination",
    "interaction",
    "recruitment",
    ]

Z02 = [
    "behavioural tests",
    "rodents",
    "systems neuroscience tools",
    "optogenetics",
    "calcium imaging",
    "preprocessing",
    "data analysis",
    "data acquisition",
    ]

Z03 = [
    "behavioural tests",
    "humans",
    "structural MRI",
    "functional MRI",
    "preprocessing",
    "data analysis",
    "data acquisition",
    ]

[project_names]

A01 = "Understanding plastin 3 and its interactors in motor neuron function and plasticity in health and disease"
A02 = "Dysregulation of the autophagy-endolysosomal system as a putative pathological mechanism behind the motor control dysfunction"
A03 = "Motor learning-induced plasticity of cerebellar Purkinje neuron connectivity"
A04 = "The role of the reward system in obesity- and ageing-associated changes of motor behaviours"
A05 = "Neural mechanisms underlying motor flexibility in fruit fly walking"
A06 = "Sensory-motor pathways controlling voluntary movements in health and disease"
A07 = "Role of synaptic lipid modulated cortical excitability in motor control"

B01 = "Developmental mechanisms affecting motor skills and motor control"
B02 = "Neural network maturation underlying top-down motor control and movement initiation in childhood and adolescence"
B03 = "Modelling neural network dynamics underlying movements in health and disease"
B04 = "Motor control under uncertainty in the healthy human brain"
B05 = "Single-case predictions of motor abilities in health and disease"

C01 = "Identification and selective stimulation of motor recovery-related functional networks after experimental stroke"
C03 = "Striatal dopamine and volitional motor control: vigour, planning, and incentive salience"
C04 = "Apraxia in Alzheimer’s disease: Plastic reorganization of praxis networks in response to chronically progressive dysfunction"
C05 = "Reorganisation of the motor system following stroke"
C06 = "Major depression as a transient functional lesion model of motor control"
C07 = "Neural networks underlying motor tic formation and suppression"

INF = "Data Management for Computational Modelling"
JRG_Gatto = "Sensorimotor ADAPtation"
JRG_Valtcheva = "Dr. Valtcheva"

X01 = "Rehabilitation of motor deficits and restoration of functional networks after mild Traumatic Brain Injury (mTBI) by transcranial Direct Current Stimulation (tDCS)"
X02 = "The interplay between sleep, depressivity and motor performance"
X03 = "Predicting the effects of deep brain stimulation of the subthalamic nucleus (STN-DBS) on gait, falls and Freezing of Gait (FOG) in patients with Parkinson’s disease"
X04 = "Modulation of cortical networks for predictive motor control by the subthalamic nucleus: from functional imaging to deep brain stimulation and recording"

Z01 = "Central Office"
Z02 = "Animal Motor Circuits Core Facility"
Z03 = "Human Motor Assessment Centre"

[funding]
[[funding.sfb1451]]
name = "Deutsche Forschungsgemeinschaft (DFG)"
identifier = "Project number 431549029"
description = "SFB1451: Key mechanisms of motor control in health and disease"
